### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by AndrewSB** [mdaiter/ActorGPU#1]
I really like the ideas behind this library. Was this pattern ever used to build anything? Are there any examples?

**Comment by AndrewSB** [comment]
Oh Matt! Whats up? I didn't realize this was you.
Your library is the first result for "gpu actor model" on google #seoonpoint

**Comment by mdaiter** [comment]
Hey!
Oh, lol, didn't know that.
Um...I had a couple of examples, but I wrote this a few years back (senior year of high school). Not too sure as to what's broken and whatnot

**Comment by lukasapaukstys** [comment]
Hi all,

I can explain the intricacies of the code if you want to give me a call.
Ultimately there are some tradeoffs that had to be taken to allow for the
program to succeed in any regard. Mainly the message box and randomization
system. The code was developed a while back as Matt mentioned, but
ultimately we concluded that agent based modeling wasn't something easily
achieved using a parrallel architecture such as Cuda.

-Lukas Paukstys
773-234-5120

**Comment by AndrewSB** [comment]
@mdaiter writing C++ for the GPU in high school 😂

@lukasapaukstys that would be awesome. I'm trying to write something similar to this on iOS using [Metal](https://developer.apple.com/metal/). Are you free to talk today? I'm asbreckenridge on google hangouts

**Comment by lukasapaukstys** [comment]
I'm not immediately free, but I might have a chunk of time a bit later in
the day. Ill try and catch you on google hangouts possibly in a few hours

**Comment by AndrewSB** [comment]
👌
